export const MEMORY_SEARCH_PT_STOPWORDS = new Set([
  "a",
  "o",
  "os",
  "as",
  "de",
  "da",
  "do",
  "das",
  "dos",
  "e",
  "em",
  "na",
  "no",
  "nas",
  "nos",
  "um",
  "uma",
  "meu",
  "minha",
  "meus",
  "minhas",
  "qual",
  "quais",
  "que",
  "agora",
  "hoje",
  "ola",
  "oi",
  "kael",
  "novo",
  "novamente",
  "aparece",
  "memoria",
  "teste",
  "so",
  "se",
  "nao",
  "sabe",
  "souber",
]);

export const MEMORY_SEARCH_PT_SYNONYMS: Record<string, string[]> = {
  time: ["clube", "torce", "torcida", "futebol"],
  clube: ["time", "torce", "futebol"],
  torce: ["time", "clube", "torcida", "futebol"],
  nome: ["chama", "chamar"],
  chamar: ["nome", "chama"],
  prefere: ["preferencia", "gosta", "favorito"],
  gosto: ["gosta", "preferencia", "favorito"],
  gosta: ["preferencia", "favorito", "curte"],
  favorito: ["preferencia", "gosta"],
  trabalho: ["empresa", "job", "projeto"],
  projeto: ["trabalho", "repo", "kael"],
};
